workflows:
  react-native-android:
        name: React Native Android
        max_build_duration: 120
        instance_type: mac_mini
        scripts:
            - name: Build Android App Bundle
              working_directory: android
              script: |
                ./gradlew bundleRelease
        artifacts:
            - build/**/outputs/bundle/**/*.aab
