workflows:
  react-native-android:
        name: React Native Android
        max_build_duration: 120
        scripts:
            - name: Build Android App Bundle
              working_directory: android
              script: |
                chmod +x gradlew && ./gradlew assembleRelease
        artifacts:
            - build/**/outputs/bundle/**/*.aab
